Update README.md
This is required, otherwise I'll get:
SynapseError: 403 - Application service cannot masquerade as this user

in journalctl -fu matrix-synapse